site_name: Hello Nextflow
repo_url: https://github.com/Sydney-Informatics-Hub/hello-nextflow
repo_name: Sydney-Informatics-Hub/hello-nextflow

nav:
  - Home: index.md
  - Environment setup:
    - setup/index.md
  - Part 1:
    - 1.0 Introduction: part1/00_intro.md
    - 1.1 Why Nextflow: part1/01_hellonextflow.md
    - 1.2 Hello World!: part1/02_helloworld.md
    - 1.3 Your first pipeline: part1/03_hellonf.md
    - 1.4 Outputs: part1/04_output.md
    - 1.5 Inputs: part1/05_inputs.md
    - 1.6 Parameters: part1/06_params.md
    - 1.7 Adding processes: part1/07_process.md
    - 1.8 Dynamic naming: part1/08_dynamic.md
  - Session 2:
    - 0. Introduction: 00_intro.md
    - 1. Indexing: 01_salmon_idx.md
    - 2. Quantification: 02_quant.md
    - 3. Quality Control: 03_qc.md
    - 4. Upscaling: 04_scale.md

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
