site_name: Hello Nextflow
repo_url: https://github.com/Sydney-Informatics-Hub/hello-nextflow
repo_name: Sydney-Informatics-Hub/hello-nextflow

nav:
  - Home: index.md
  - Environment setup:
    - setup/index.md
  - Day 1:
    - 1.0 Introduction: day1/00_intro.md
    - 1.1 Hello World!: day1/01_helloworld.md
    - 1.2 Our first pipeline: day1/02_hellonf.md
    - 1.3 Outputs: day1/03_output.md
    - 1.4 Inputs: day1/04_inputs.md
    - 1.5 Parameters: day1/05_params.md
    - 1.6 Adding processes: day1/06_process.md
    - 1.7 Dynamic naming: day1/07_dynamic.md
  - Day 2:
    - 2.0 Introduction: day2/00_intro.md
    - 2.1 TBC: day2/01_salmon_idx.md
    - 2.2 TBC: day2/02_quant.md
    - 2.3 TBC: day2/03_fastqc.md
    - 2.4 TBC: day2/04_multiqc.md
    - 2.5 TBC: day2/05_scale.md

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
