site_name: Hello Nextflow
repo_url: https://github.com/Sydney-Informatics-Hub/hello-nextflow
repo_name: Sydney-Informatics-Hub/hello-nextflow

nav:
  - Home: index.md
  - Environment setup:
    - setup/index.md
  - Session 1:
    - 1.0 Introduction: session1/00_intro.md
    - 1.1 Hello World!: session1/01_helloworld.md
    - 1.2 Our first pipeline: session1/02_hellonf.md
    - 1.3 Outputs: session1/03_output.md
    - 1.4 Inputs: session1/04_inputs.md
    - 1.5 Parameters: session1/05_params.md
    - 1.6 Adding processes: session1/06_process.md
    - 1.7 Dynamic naming: session1/07_dynamic.md
  - Session 2:
    - 2.0 Introduction: session2/00_intro.md
    - 2.1 TBC: session2/01_salmon_idx.md
    - 2.2 TBC: session2/02_quant.md
    - 2.3 TBC: session2/03_fastqc.md
    - 2.4 TBC: session2/04_multiqc.md
    - 2.5 TBC: session2/05_scale.md

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
